on:
  workflow_dispatch
permissions:
  id-token: write
  contents: read
jobs:
  automerge-action:
    runs-on: ubuntu-latest
    name: automerge
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: send email when merge fail(test)
        if: success()
        uses: dsfx3d/action-aws-ses@v1
        with:
          # email subject
          subject: 'sagemaker-python-sdk-feedstock merge fail notification'
          # email body as text
          body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
          # comma-separated string, send email to
          to: 'liujiaor@amazon.com'
