on:
  workflow_dispatch
jobs:
  automerge-action:
    runs-on: ubuntu-latest
    name: automerge
    permissions:
      id-token: write
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::312598714048:role/ses-github-actions-role
          output-credentials: true
          audience: https://sts.us-east-1.amazonaws.com
      - name: get caller identity
        if: success()  
        run: |
            aws sts get-caller-identity
            aws ses send-email \
              --from "liujiaor@example.com" \
              --to "liujiaor@amazon.com" \
              --message "Subject={Data=from ses,Charset=utf8},Body={Text={Data=ses says hi,Charset=utf8},Html={Data=,Charset=utf8}}"
